### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by MarwanDev** [emhamza/Space-X#25]
In this milestone we: 
- Copied the Kanban board on the Github Project <a href="https://github.com/emhamza/Space-X/projects/1">here</a>
- There are 2 people in this team @emhamza : Rockets  & @MarwanDev : Missions

**Comment by omarsalem7** [comment]
Hi team 😊, 
# STATUS: APPROVED! 🥇 💯 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
